// <auto-generated />
namespace SCBWIFloridaJune.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class lisawheeler : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lisawheeler));
        
        string IMigrationMetadata.Id
        {
            get { return "201306120630571_lisawheeler"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
